######################################################################
# Automatically generated by qmake (3.0) dom. nov. 16 10:06:20 2014
######################################################################

TEMPLATE = app
TARGET = Calc
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += BasicCalc.h CalcWidget.h
SOURCES += BasicCalc.cpp CalcWidget.cpp main.cpp
