######################################################################
# Automatically generated by qmake (3.0) jue. nov. 13 15:40:38 2014
######################################################################

TEMPLATE = app
TARGET = Hello
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += HelloWidget.h
SOURCES += HelloWidget.cpp main.cpp
